spring:
  application:
    name: takehome
  cloud:
    config:
      allow-override: true
      override-system-properties: false
  security:
    oauth2:
      resource:
        id: takehome
        token-info-uri: ${AUTH_SERVER_URI:http://localhost:8090/takehomeoauth}/oauth2/check_token
      client:
        client-id: takehomeuserclient1
        client-secret: 83AN9Q7m0sZV  
redis:
  database: 0
  host: ${REDIS_SERVER_HOST:localhost}
  port: ${REDIS_SERVER_POST:6379}
  password: ${REDIS_SERVER_PASSWORD:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81}
  timeout: 60000
server:
  servlet:
    context-path: /takehome
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_AND_DISCOVERY_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
takehome:
  continentDataFilePath: classpath:continent-data.json
  countryDataFilePath: classpath:country-data.json