spring:
  application:
    name: takehomegateway
  profiles:
    active: ${APPLICATION_ENV:prod}
  cloud:
    config:
      uri: ${CONFIGURATION_SERVER_URI:http://localhost:8088/takehome-configuration}
      username: takehomeconfig
      password: eDbAM29d8f9z
      failFast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 10000
        maxAttempts: 20
  config:
    import: configserver:${CONFIGURATION_SERVER_URI:http://localhost:8088/takehome-configuration}